services:

  backend:
    build: ./backend
    env_file: .env

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile