services:

  backend:
    build: ./backend
    env_file: .env
    restart: always

  qdrant:
    image: qdrant/qdrant:v1.3.2
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    profiles:
      - local
